### ISSUE TITLE
 index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by ApuApsara** [mokosaur/iris-recognition#2]
I am new to python and github.This is the first time i am using it.
I am getting an error when I run coding.py
Someone help me fix this error 
line 118, in <module>
    image = cv2.imread(data[0])
IndexError: index 0 is out of bounds for axis 0 with size 0
[coding.txt](https://github.com/mokosaur/iris-recognition/files/1934325/coding.txt)

**Comment by mokosaur** [comment]
This is because load_utiris() from datasets.py returns an empty list. First, you need to download the dataset from https://utiris.wordpress.com/ and put it into "UTIRIS V.1" directory. Alternatively, you can create your own loader that loads your data.

**Comment by ApuApsara** [comment]
Thank you..
