### ISSUE TITLE
problem in mokasaur compilation

### ISSUE THREAD

**Issue by nasreen534** [mokosaur/iris-recognition#5]
raceback (most recent call last):
  File "C:/Users/naseeruddin/PycharmProjects/iris-recognition/recognition.py", line 116, in <module>
    image = cv2.imread(data[0])
IndexError: index 0 is out of bounds for axis 0 with size 0

I tried all solutions like the opencv-python package, create a directory for utirisv.1, activation of conda, virtual environment but..same error

**Comment by mokosaur** [comment]
Probably this error shows up because you have not downloaded the dataset. First, you need to download the data from [https://utiris.wordpress.com/](https://utiris.wordpress.com/) and put it into "UTIRIS V.1" directory. Another possibility is to adjust the dataset of your choice to this format.
